fix dockerfile and readme
ONSdigital/sdx-validate pull request #44
Opened 2017-06-07 10:32 UTC by andrewmil

Added common functionality and updated logger format

2017-06-07 10:42 UTC, shahi645 submitted a review, later dismissed

2017-06-07 10:45 UTC, JamesGardiner requested changes

2017-06-07 10:45 UTC, JamesGardiner commented on Makefile
> +	cd .. && pip3 uninstall -y sdx-common && pip3 install -I ./sdx-common
This will break if sdx-common isn't already installed. See downstream-ctp for a fix.

2017-06-07 10:45 UTC, JamesGardiner commented on README.md
> +Using virtualenv and pip, create a new environment and install the sdx-common library from a local directory:
Should be instructions on using Makefile

2017-06-08 11:21 UTC, shahi645 approved these changes

2017-06-08 11:22 UTC, JamesGardiner approved these changes

2017-06-08 11:22 UTC, merged